name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Install JSHint
        run: npm install -g jshint

      - name: Run Linter
        run: jshint .

      - name: Complete job
        run: echo "Build successful"